name: 'Deploy to Azure App Service'

on:
  workflow_dispatch:

env:
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  AZURE_WEBAPP_NAME: PSDeployDemo

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release
      
    - name: Publish
      run: dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'

    
    - name: Upload published artifact
      uses: actions/upload-artifact@v4
      with:
        name: published-app
        path: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'

    - run: echo 'Publish output path ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
      
    - name: Deploy
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: 'development'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
        
        
